#include "../../gpucsl/pc/cuda/helpers/math_helpers.cu"
#include <gtest/gtest.h>

// It is only possible to include and test files that do not contain
// device specific code like threadIdx.x or atomicAdd(...), as these can not
// be provided for these tests, as they are run on the CPU
// If one includes these files, they need to be hidden to the compiler, e.g. by
// preprocessor macros

TEST(Helpertest, BinomialCoefficient) {
    EXPECT_EQ(binomial_coefficient(2, 3), 0);
    EXPECT_EQ(binomial_coefficient(3, 2), 3);
    EXPECT_EQ(binomial_coefficient(5, 2), 10);
    EXPECT_EQ(binomial_coefficient(20, 10), 184756);
    EXPECT_EQ(binomial_coefficient(30, 20), 30045015);
    EXPECT_EQ(binomial_coefficient(30, 30), 1);
}


// Examples generated by python:
// ```
//    from scipy import stats
//    expected = 1 - stats.chi2.cdf(x, y)
// ```
TEST(Helpertest, PChiSquared) {
    EXPECT_FLOAT_EQ(pchisq(3, 2), 0.22313016014842982);
    EXPECT_FLOAT_EQ(pchisq(20, 10), 0.02925268807696113);
    EXPECT_FLOAT_EQ(pchisq(0, 1), 1.0);
    EXPECT_FLOAT_EQ(pchisq(10, 10), 0.4404932850652121);
    EXPECT_FLOAT_EQ(pchisq(0.2, 3), 0.9775892977616494);
}
