
name: Lint CUDA

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, Linux, X64]

    steps:
    - uses: actions/checkout@v3
    - name: Lint with clang-tidy and clang-format
      run: |
        ./scripts/lint-cuda.sh
