
name: Test CUDA Device Functions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [self-hosted, Linux, X64, gpu]

    steps:
    - uses: actions/checkout@v3
    - name: Test with GoogleTest
      run: |
        ./scripts/test-cuda.sh
